### ISSUE TITLE
High memory usage of torch compared to flax

### ISSUE THREAD

**Issue by phhusson** [kuprel/min-dalle#11]
Hi,

Thanks for this project, you gave me hope to give my AMD GPU some fun :-) (torch is much easier to get to work on it than XLA)

That being said, it doesn't work yet, because the torch variant eats much more RAM than the flax one:
```
/usr/bin/time -v python image_from_text.py --text='a comfy chair that looks like an avocado' --torch --seed=4
        Maximum resident set size (kbytes): 21.096.396

/usr/bin/time -v python image_from_text.py --text='a comfy chair that looks like an avocado' --seed=4
        Maximum resident set size (kbytes): 4.152.744
```

Would you have some pointers as to how  to optimize that?

**Comment by kuprel** [comment]
I added `torch.set_grad_enabled(False)` and it seems to have significantly reduced memory usage with torch
