### ISSUE TITLE
ExtraData: unpack(b) received extra data.

### ISSUE THREAD

**Issue by phatdoyle** [kuprel/min-dalle#34]
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/16765881/176480315-5666b3c3-5afe-4cff-9e8c-36765c760ed3.png">

Does anyone know how to mitigate this error?

**Comment by kuprel** [comment]
It might have something to do with git LFS.  `curl` is now used to download vqgan.  Do you have that problem if you use the latest commit?
