### ISSUE TITLE
Average creation time has more than doubled for non-mega on torch

### ISSUE THREAD

**Issue by w4ffl35** [kuprel/min-dalle#42]
Latest branch (using torch, not mega rtx 2080s 8g)

```
It took 0:01:14.897944 to generate F10 images

Average time to generate an image: 0:00:07.489794
```

Rolled back to 3837710

```
It took 0:00:33.533277 to generate F10 images

Average time to generate an image: 0:00:03.353328
```

Something between 3837710 and HEAD has more than doubled average creation time @kuprel

_Originally posted by @w4ffl35 in https://github.com/kuprel/min-dalle/issues/39#issuecomment-1171324154_

**Comment by kuprel** [comment]
Thanks for catching that.  Is the commit I just made faster?

**Comment by kuprel** [comment]
I've been running this command: `time python3 image_from_text.py --torch --token_count=4`

It only generates 4 tokens instead of all 256, and times it
