### ISSUE TITLE
Add PyPI install

### ISSUE THREAD

**Issue by davidmezzetti** [kuprel/min-dalle#44]
First off, great project, thank you for building this!

Have you considered building a package for PyPI? The models are available on the [Hugging Face Hub](https://huggingface.co/dalle-mini) and the [Hugging Face Hub package](https://github.com/huggingface/huggingface_hub) can be used to programmatically download/cache the models.

Another idea is that encoder.pt and decoder.pt could also be uploaded to a new model on the Hub so they don't need to be dynamically converted at runtime for the Torch model.

One last thing to consider is changing prints to log statements, so they could be turned off if desired. 

General idea is someone can run `pip install` then be up and running regardless of the runtime platform (Windows/Linux/macOS).

**Comment by kuprel** [comment]
Thanks!  I like your idea of uploading the pt files to the HF hub, doing that now.  It will save a lot of time converting from flax and get rid of a lot of ugly conversion code.  Will look into the PyPI install

**Comment by kuprel** [comment]
The colab now runs purely in torch and downloads pre-converted pytorch parameters from the HF hub.  Saves a lot of time.

**Comment by davidmezzetti** [comment]
That's great! Definitely seems simpler now.

If you wanted to programmatically download models vs depending on running curl you could add the huggingface_hub library and do something like this:

```python
from huggingface_hub import hf_hub_url, cached_download

config_file_url = hf_hub_url("kuprel/min-dalle", filename="vocab.json")
cached_download(config_file_url)
```

https://huggingface.co/docs/huggingface_hub/how-to-downstream

This would also open up option to parameterize the model loaded (defaulting to yours) and let someone load an alternative model. 

Could also consider having two hf model projects, one for mini and one for mega.

**Comment by kuprel** [comment]
I added the package to PyPI and now the entire setup process is `pip install min-dalle`.  The model parameters are downloaded as needed with just the `requests` library.  Thanks for the suggestions.  I should probably also add a flag for `verbose` to prevent the print statements

**Comment by w4ffl35** [comment]
awesome thank you for doing this @kuprel

**Comment by davidmezzetti** [comment]
This is great! Thank you for doing this. I also see the verbose flag now. I'll close this issue.

I've used your work for an example notebook that generates an image from a webpage summary. You can see it here. Thanks again for creating this library!

https://colab.research.google.com/github/neuml/txtai/blob/master/examples/35_Pictures_are_worth_a_thousand_words.ipynb#scrollTo=uDHUDqjptyzA
https://dev.to/neuml/pictures-are-a-worth-a-thousand-words-144k

**Comment by kuprel** [comment]
Wow that's really cool

**Comment by davidmezzetti** [comment]
Thanks. Good luck with this project, looking forward to seeing it grow!
