### ISSUE TITLE
Use a virtual environment to install dependecies

### ISSUE THREAD

**Issue by atoav** [kuprel/min-dalle#5]
A short gaze at `setup.sh` told me that this script installs the dependencies in `requirements.txt` directly to the systems python installation. This is typically not considered good practise (as far as I know), so it might be a good idea to prompt users for permission first.

Alternatively installing everything to a venv might be a different solution that keeps the system python "clean".

**Comment by toabi** [comment]
The script works though if you first initialize and activate a virtual env before running the script.

**Comment by kuprel** [comment]
I like @toabi 's suggestion
