### ISSUE TITLE
Add missing requirements on pip install

### ISSUE THREAD

**Issue by w4ffl35** [kuprel/min-dalle#50]
The following requirements are missing in the official pip installation and must be installed separately

- PIL
- numpy
- requests

**Comment by w4ffl35** [comment]
maybe these are left out purposely to make the library less opinionated? 

i'm not sure what standard practice is for pip (i think you are meant to include all requirements in the installation). if you do choose to leave them out of the installation, i would at least recommend mentioning those requirements in the README

**Comment by kuprel** [comment]
I updated the `setup.py` file to require these, thanks
