### ISSUE TITLE
Is inpainting a possibility?

### ISSUE THREAD

**Issue by ExponentialML** [kuprel/min-dalle#52]
Hey, amazing work! Would there be a possibility of integrating text guided image completion or in panting with this model? If so, what would be the general direction to go to for implementation?
 
I'm assuming the model needs to be fed a rough estimate of an image's latent data, then fill in the missing pieces. I can give it a go if there are leads in the right direction, Thanks!

**Comment by kuprel** [comment]
This model doesn't support inpainting
