### ISSUE TITLE
Streaming intermediate images?

### ISSUE THREAD

**Issue by sabetAI** [kuprel/min-dalle#56]
Is it possible to publish an update of the model that supports streaming intermediate images during reverse diffusion ie with an iterator? Would greatly help UX if the user can see their image form while they're waiting for the process to finish.

**Comment by kuprel** [comment]
This isn't a diffusion model so that wouldn't work

**Comment by sabetAI** [comment]
Diffusion models iteratively update the image over multiple steps. These iterates can be streamed out (ie see [glide demo](https://replicate.com/jack000/glid-3-xl)). 'Reverse diffusion' is simply the image generation step, which is what your model is doing during inference. Can you update the code to output intermediate images?

**Comment by sabetAI** [comment]
Using the term 'reverse diffusion' might have caused some confusion with what I was asking.

**Comment by iScriptLex** [comment]
This model is **not** like glide or VQGAN+CLIP.
DALL-E works on a entirely different principle. The image is generated with tiny squares (tokens), square by square, from left to right and top to bottom. It does not change all image at once at every iteration like diffuse models. Every iteration it just fills another tiny bit of the empty area with the completely ready tiny portion of the final image.

**Comment by sabetAI** [comment]
Ah good point, I made assumptions about the model architecture. Even if it's outputting autoregressively, tokens can still be streamed out to incrementally update a canvas a pixel at a time. The main use-case here is so to show intermediate results to the user, as waiting kills the UX.

**Comment by kuprel** [comment]
It might be possible to generate the images each time a row of tokens is decoded, and use some kind of blank token for the missing rows

**Comment by sabetAI** [comment]
@kuprel yes exactly. Also would it be more efficient just to stream rows of tokens and have the client handle everything else? Want to minimize latency that streaming may add.

**Comment by w4ffl35** [comment]
> This model is **not** like glide or VQGAN+CLIP. DALL-E works on a entirely different principle. The image is generated with tiny squares (tokens), square by square, from left to right and top to bottom. It does not change all image at once at every iteration like diffuse models. Every iteration it just fills another tiny bit of the empty area with the completely ready tiny portion of the final image.

this would still look cool while it was loading

**Comment by sabetAI** [comment]
@w4ffl35 can you quantify marginal latency/bandwidth costs? Loaders *may* work for one-time uses, but users will churn if they're stuck looking at loaders 95% of the time. See [urzas.ai](urzas.ai) for example of UX with intermediate outputs. Imo if a flag was made available it would be hugely valuable for devs.

**Comment by w4ffl35** [comment]
@sabetAI those are great points

**Comment by kuprel** [comment]
Ok I got it working in the colab now I just have to figure out how to get it on replicate.  An intermediate image count of 8 only adds a couple seconds to the overall decoding time on the P100

**Comment by kuprel** [comment]
Here's what it looks like ![animated](https://user-images.githubusercontent.com/7465979/177213087-01d62ba2-6286-4da7-b46e-1e27476d4ad9.gif)

**Comment by sabetAI** [comment]
@kuprel so good 👏. When can you merge?

**Comment by kuprel** [comment]
I merged it.  You can try it in the colab.  Hopefully will get it onto replicate by tomorrow

**Comment by kuprel** [comment]
Ok it's live on replicate now
