### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by kuprel** [kuprel/min-dalle#63]
When running in high load settings on the A100 this error comes up after about 10 minutes.  This happens on replicate and on the discord bot.  The best fix so far is just to restart the server every 10 minutes.  If anyone has a better fix for it, please post it here.  Thanks

**Comment by iScriptLex** [comment]
Is this happening on your own server or in that buggy Google Colab that likes to give weird errors?

**Comment by kuprel** [comment]
Fix was to clamp the image and text tokens within their bounds.  Either the text or image tokens must sometimes exceed their vocab count, I'm not sure which
