### ISSUE TITLE
Lossless option for the replicate predictor.

### ISSUE THREAD

**Issue by ImagicTheCat** [kuprel/min-dalle#68]
Hi,

Right now the output is lossy with JPG, it would be nice to have an option to output to a lossless format like PNG (if it is possible).

Thanks.

**Comment by kuprel** [comment]
Ok, the latest version outputs a png for the final image

**Comment by ImagicTheCat** [comment]
Nice, thanks.

**Comment by kuprel** [comment]
It actually adds up to 10 seconds (for 9x9) saving as png so I'm making it an argument that defaults to false.  You will have to set output_png to true to get a png once this new version has uploaded.

**Comment by ImagicTheCat** [comment]
In my workflow, I now export to uncompressed TGA files. Files are ~2x the size of PNG, but it should be faster. In most cases less compute will probably be more valuable than twice the bandwidth (rental cost, responsiveness). But it seems unsupported by browsers, so I don't know how it could work with replicate.
