### ISSUE TITLE
Undeclared requirement - wandb api key

### ISSUE THREAD

**Issue by mikewarot** [kuprel/min-dalle#7]
I have no idea what wandb.ai is, but that should be declared in the requirements, OR a way around it should be offered.

**Comment by GuillaumeRochette** [comment]
@mikewarot If you want to avoid having to sign up or sign in to `wandb` you can replace the line `wandb.login()` with `! wandb offline`.

**Comment by kuprel** [comment]
The colab notebook has been updated to login anonymously
