### ISSUE TITLE
Changing image size?

### ISSUE THREAD

**Issue by patrickjonesdotca** [kuprel/min-dalle#72]
Would love to know where to change the code to allow for larger image sizes than 256x256.
Better yet would be the ability to change them from the Colab.

**Comment by kuprel** [comment]
How does it look?

**Comment by iScriptLex** [comment]
@neverix, ruDALL-E doesn't use pass-through recurrent attention, so the result depends only on the input tokens sequence.
But DALL-E mini uses attention state as parameter, and this attention context changes recurrently during the generation. So I doubt it can process sliding windows effectively.

**Comment by neverix** [comment]
@iScriptLex Well, I implemented the functional caching so I would know :sweat_smile:. It's passed around in [a similar way](https://github.com/ai-forever/ru-dalle/blob/38c6abb39e40f0c78c3f4bb00de672a28b6e7b7d/rudalle/dalle/transformer.py#L129), and nothing needs to be changed in the current DALL-E mini codebase to incorporate it (so it can be like a colab notebook).

**Comment by neverix** [comment]
@kuprel Here's a sample 384px generation without upscaling
![image](https://user-images.githubusercontent.com/46641404/179257586-5697cdab-4153-404c-a64e-bee5777ca979.png)
