### ISSUE TITLE
What is this visual artefact? 

### ISSUE THREAD

**Issue by dza6549** [kuprel/min-dalle#78]
Please note the 'chainmesh and embossed circle' artefact that is overlaid on this set of images. I also found this artefact from time to time in the dalle-mini/craiyon demo. Does anyone know what it is? 

![min-dalle-iter-8](https://user-images.githubusercontent.com/27390320/179384288-7937d480-4c0a-440b-a8e0-5ed8d3c27b64.jpg)

**Comment by neverix** [comment]
Might be stock photo watermarks from the dataset

**Comment by kuprel** [comment]
<img width="660" alt="Screenshot 2022-07-17 at 7 07 33 AM" src="https://user-images.githubusercontent.com/7465979/179405744-4895249d-acfd-4f0f-92aa-7330a49f35a9.png">
