### ISSUE TITLE
New Replicate Github sign-in required and pricing question

### ISSUE THREAD

**Issue by dza6549** [kuprel/min-dalle#87]
Can you please clarify how the new Replicate Github sign-in required will work with Replicate pricing? Will I be encouraged to sign up for a Replicate pricing plan? Is there a daily limit of 'free' Replicate runs? How much compute time does a single image consume? In the long run, will it be better for me to try and host this model myself?

I'm researching how to engineer and manipulate text prompts and Replicate min-dalle allows me to iterate permutations rapidly.

Thank you

**Comment by kuprel** [comment]
Replicate added that requirement, not me. You should ask them. There's also the hugging face one you can use without logging in

**Comment by dza6549** [comment]
Ah. I see. Thank you for your reply and the HuggingFace tip. And for making this model available.

**Comment by FlashlightET** [comment]
> Is there a daily limit of 'free' Replicate runs?
I last used the site 3-5 days ago, not logged in. Had to log in today, immediately required me to pay.
